server:
  port: 8085
  forward-headers-strategy: framework

spring:
  application:
    name: gatewaysosmongarage

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: messagerie-service
              uri: https://sos-mon-garage-messagerie-notification-production-5b5b.up.railway.app
              predicates:
                - Path=/V2/**
            - id: garage-service
              uri: https://sosmongarage-production-d435.up.railway.app
              predicates:
                - Path=/V1/**

springdoc:
  swagger-ui:
    path: /swagger-ui
    use-root-path: true
    urls:
      - name: Messagerie Service
        url: /V2/v3/api-docs
      - name: Garage Service
        url: /V1/v3/api-docs
  api-docs:
    enabled: false
